package japicmp.model;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlEnum;

@XmlEnum
public enum JApiCompatibilityChange {
	CLASS_REMOVED(false, false),
	CLASS_NOW_ABSTRACT(false, false),
	CLASS_NOW_FINAL(false, false),
	CLASS_NO_LONGER_PUBLIC(false, false),
	CLASS_TYPE_CHANGED(false, false),
	CLASS_NOW_CHECKED_EXCEPTION(true, false),
	SUPERCLASS_REMOVED(false, false),
	SUPERCLASS_ADDED(true, true),
	SUPERCLASS_MODIFIED_INCOMPATIBLE(false, false),
	INTERFACE_ADDED(true, true),
	INTERFACE_REMOVED(false, false),
	METHOD_REMOVED(false, false),
	METHOD_REMOVED_IN_SUPERCLASS(false, false),
	METHOD_LESS_ACCESSIBLE(false, false),
	METHOD_LESS_ACCESSIBLE_THAN_IN_SUPERCLASS(false, false),
	METHOD_IS_STATIC_AND_OVERRIDES_NOT_STATIC(false, false),
	METHOD_RETURN_TYPE_CHANGED(false, false),
	METHOD_NOW_ABSTRACT(false, false),
	METHOD_NOW_FINAL(false, false),
	METHOD_NOW_STATIC(false, false),
	METHOD_NO_LONGER_STATIC(false, false),
	METHOD_ADDED_TO_INTERFACE(true, false),
	METHOD_NOW_THROWS_CHECKED_EXCEPTION(true, false),
	METHOD_ABSTRACT_ADDED_TO_CLASS(true, false),
	METHOD_ABSTRACT_ADDED_IN_SUPERCLASS(true, false),
	METHOD_ABSTRACT_ADDED_IN_IMPLEMENTED_INTERFACE(true, false),
	FIELD_STATIC_AND_OVERRIDES_STATIC(false, false),
	FIELD_LESS_ACCESSIBLE_THAN_IN_SUPERCLASS(false, false),
	FIELD_NOW_FINAL(false, false),
	FIELD_NOW_STATIC(false, false),
	FIELD_NO_LONGER_STATIC(false, false),
	FIELD_TYPE_CHANGED(false, false),
	FIELD_REMOVED(false, false),
	FIELD_REMOVED_IN_SUPERCLASS(false, false),
	FIELD_LESS_ACCESSIBLE(false, false),
	CONSTRUCTOR_REMOVED(false, false),
	CONSTRUCTOR_LESS_ACCESSIBLE(false, false),
	ANNOTATION_ADDED(true, true),
	ANNOTATION_REMOVED(true, true),
	ANNOTATION_MODIFIED(true, true),

	REST_HTTP_PROVIDER_ADDED(false, false),
	REST_HTTP_PROVIDER_REMOVED(false, false),
	REST_HTTP_PROVIDER_MODIFIED(false, false),
	REST_HTTP_PRODUCES_ADDED(false, false),
	REST_HTTP_PRODUCES_REMOVED(false, false),
	REST_HTTP_PRODUCES_MODIFIED(false, false),
	REST_HTTP_FORM_PARAM_ADDED(false, false),
	REST_HTTP_FORM_PARAM_REMOVED(false, false),
	REST_HTTP_FORM_PARAM_MODIFIED(false, false),
	REST_HTTP_CONSUMES_ADDED(false, false),
	REST_HTTP_CONSUMES_REMOVED(false, false),
	REST_HTTP_CONSUMES_MODIFIED(false, false),
	REST_HTTP_HEADER_PARAM_ADDED(false, false),
	REST_HTTP_HEADER_PARAM_REMOVED(false, false),
	REST_HTTP_HEADER_PARAM_MODIFIED(false, false),
	REST_HTTP_DEFAULT_VALUE_ADDED(false, false),
	REST_HTTP_DEFAULT_VALUE_REMOVED(false, false),
	REST_HTTP_DEFAULT_VALUE_MODIFIED(false, false),
	REST_HTTP_PARAM_CONVERTER$LAZY_ADDED(false, false),
	REST_HTTP_PARAM_CONVERTER$LAZY_REMOVED(false, false),
	REST_HTTP_PARAM_CONVERTER$LAZY_MODIFIED(false, false),
	REST_HTTP_DELETE_ADDED(false, false),
	REST_HTTP_DELETE_REMOVED(false, false),
	REST_HTTP_DELETE_MODIFIED(false, false),
	REST_HTTP_PATH_PARAM_ADDED(false, false),
	REST_HTTP_PATH_PARAM_REMOVED(false, false),
	REST_HTTP_PATH_PARAM_MODIFIED(false, false),
	REST_HTTP_SUSPENDED_ADDED(false, false),
	REST_HTTP_SUSPENDED_REMOVED(false, false),
	REST_HTTP_SUSPENDED_MODIFIED(false, false),
	REST_HTTP_ENCODED_ADDED(false, false),
	REST_HTTP_ENCODED_REMOVED(false, false),
	REST_HTTP_ENCODED_MODIFIED(false, false),
	REST_HTTP_PRE_MATCHING_ADDED(false, false),
	REST_HTTP_PRE_MATCHING_REMOVED(false, false),
	REST_HTTP_PRE_MATCHING_MODIFIED(false, false),
	REST_HTTP_PATH_ADDED(true, true),
	REST_HTTP_PATH_REMOVED(false, false),
	REST_HTTP_PATH_MODIFIED(false, false),
	REST_HTTP_APPLICATION_PATH_ADDED(false, false),
	REST_HTTP_APPLICATION_PATH_REMOVED(false, false),
	REST_HTTP_APPLICATION_PATH_MODIFIED(false, false),
	REST_HTTP_PUT_ADDED(true, true),
	REST_HTTP_PUT_REMOVED(false, false),
	REST_HTTP_PUT_MODIFIED(false, false),
	REST_HTTP_MATRIX_PARAM_ADDED(false, false),
	REST_HTTP_MATRIX_PARAM_REMOVED(false, false),
	REST_HTTP_MATRIX_PARAM_MODIFIED(false, false),
	REST_HTTP_NAME_BINDING_ADDED(true, true),
	REST_HTTP_NAME_BINDING_REMOVED(false, false),
	REST_HTTP_NAME_BINDING_MODIFIED(false, false),
	REST_HTTP_CONSTRAINED_TO_ADDED(false, false),
	REST_HTTP_CONSTRAINED_TO_REMOVED(false, false),
	REST_HTTP_CONSTRAINED_TO_MODIFIED(false, false),
	REST_HTTP_BEAN_PARAM_ADDED(false, false),
	REST_HTTP_BEAN_PARAM_MODIFIED(false, false),
	REST_HTTP_BEAN_PARAM_REMOVED(false, false),
	REST_HTTP_OPTIONS_ADDED(true, true),
	REST_HTTP_OPTIONS_REMOVED(false, false),
	REST_HTTP_OPTIONS_MODIFIED(false, false),
	REST_HTTP_GET_ADDED(true, true),
	REST_HTTP_GET_REMOVED(false, false),
	REST_HTTP_GET_MODIFIED(false, false),
	REST_HTTP_POST_ADDED(true, true),
	REST_HTTP_POST_REMOVED(false, false),
	REST_HTTP_POST_MODIFIED(false, false),
	REST_HTTP_HEAD_ADDED(true, true),
	REST_HTTP_HEAD_REMOVED(false, false),
	REST_HTTP_HEAD_MODIFIED(false, false),
	REST_HTTP_CONTEXT_ADDED(false, false),
	REST_HTTP_CONTEXT_REMOVED(false, false),
	REST_HTTP_CONTEXT_MODIFIED(false, false),
	REST_HTTP_QUERY_PARAM_ADDED(true, true),
	REST_HTTP_QUERY_PARAM_REMOVED(false, false),
	REST_HTTP_QUERY_PARAM_MODIFIED(false, false),
	REST_HTTP_COOKIE_PARAM_ADDED(true, true),
	REST_HTTP_COOKIE_PARAM_REMOVED(false, false),
	REST_HTTP_COOKIE_PARAM_MODIFIED(false, false);

	private final boolean binaryCompatible;
	private final boolean sourceCompatible;

	JApiCompatibilityChange(boolean binaryCompatible, boolean sourceCompatible) {
		this.binaryCompatible = binaryCompatible;
		this.sourceCompatible = sourceCompatible;
	}

	@XmlAttribute(name = "binaryCompatible")
	public boolean isBinaryCompatible() {
		return binaryCompatible;
	}

	@XmlAttribute(name = "sourceCompatible")
	public boolean isSourceCompatible() {
		return sourceCompatible;
	}
}
